POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "180f438b-9d08-4b06-a569-b229ccd84ad5"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "208429b3-0598-4751-90c3-447a3d3565c9",
    "account_id_to": "09ef7fcd-4dd0-4513-8fa0-b6844f4ecb48",
    "amount": 1
}
