POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "180f438b-9d08-4b06-a569-b229ccd84ad5"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "c4814972-f4ea-43d6-9934-17ae6b22ecd0",
    "account_id_to": "ee66ff4f-8ca1-4c64-babf-3c486df23fd2",
    "amount": 1
}
